### ISSUE TITLE
Upgrade version of .Net

### ISSUE THREAD

**Issue by FiB3** [SalesforceLabs/ampscript-core#19]
Hello!
there's one thing I noticed during the installation - the extension requires v7 of the .NET.
The SFDX CLI requires v8, which leads to a bit of duplication - would be nice to use the same version for both.

**Comment by garek007** [comment]
How did you get this to work? I've tried installing 7, but still not working.

**Comment by lbuesching** [comment]
This is fixed with #24 and will be released with the 0.0.6 release.
